


assembly_body         ::= ( assembly_element )*
assembly_element      ::= namespace_declaration
                        | namespace_part
                        | ignorable

namespace_declaration ::= access_modifier
                        & ignorable+
                        & "namespace"
                        & ignorable+
                        & identifier
                        & ignorable*
                        & "{"
                        & namespace_body
                        & "}"

namespace_part        ::= "extend"
                        & ignorable+
                        & "namespace"
                        & ignorable+
                        & q_identifier
                        & ignorable*
                        & "{"
                        & namespace_body
                        & "}"

namespace_body         ::= ( namespace_body_element ) *
namespace_body_element ::= ignorable
                         | namespace_declaration
                         | namespace_part
                         | class_declaration
                         | class_part
                         | function_declaration
                         | operator_declaration

class_declaration      ::= access_modifier
                         & ignorable+
                         & "class"
                         & identifier
                         & ignorable*
                         & "{"
                         & class_body
                         & "}"

class_part             ::= "in class"
                         & ignorable+
                         & q_identifier
                         & ignorable*
                         & "{"
                         & class_body
                         & "}"



access_modifier ::= "public" | "private" | "protected"


ignorable ::= whitespace | comment
whitespace ::= ( space | tab | linebreak )+
space      ::= " "
tab        ::= "\t"
linebreak  ::= "\r\n"
             | "\r"
             | "\n"
comment    ::= line_comment
             | block_comment
line_comment ::= "//" & ... & linebreak
